### ISSUE TITLE
Check scaling of website on mobile and laptop screens

### ISSUE THREAD

**Issue by philiphand** [stiftelsen-effekt/main-site#307]

**Comment by philiphand** [comment]
![Image](https://user-images.githubusercontent.com/44257880/176169144-77aaca4f-daec-4167-bd68-ae6613744cdf.png)

**Comment by JorgenLjones** [comment]
Min Side - first page, desktop half screen width

![Image](https://user-images.githubusercontent.com/12774906/181738248-03ee0e25-cf34-436e-ab94-309f8c19b1f8.png)

**Comment by JorgenLjones** [comment]
Min Side - first page (Total), desktop half screen width

![Image](https://user-images.githubusercontent.com/12774906/181738755-7d551ae4-e29b-4521-8c81-1d40032bcf35.png)

**Comment by EliseAndresen** [comment]
> Overlapping text Min Side - first page, desktop half screen width
> 
> ![Image](https://user-images.githubusercontent.com/12774906/181738248-03ee0e25-cf34-436e-ab94-309f8c19b1f8.png)

- Min side -> donasjoner -> screenwidth 1180 or less.
	H2 font size scale with vw and hits text above     	
	font-size: 10vw;

**Comment by EliseAndresen** [comment]
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/112557835/195334295-657cdc65-232a-4789-a590-383f6c119eb2.png">

Paragraf not aligned.

https://gieffektivt.no/full-oversikt  ->  window width 1180 or less
Max width of "alt samlet på samme sted" is not changed when title and ingress gets left aligned. (title and ingress changes on 1180 but paragraph keeps max-width at any size)

**Comment by EliseAndresen** [comment]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/112557835/195338219-03a3cdc6-35ad-4ccb-9a0a-82fa1d419bde.png">

Emails and titles go over one line on both bigger and smaller view sizes.
Can we determine where they break? Or have fewer images per line so that image boxes can be larger all the time and the text fits.

**Comment by EliseAndresen** [comment]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/112557835/195348330-58a53781-36ce-4621-8efa-9a9f68ac632a.png">

Articles without date need more space above title when screen is 1180 or less

**Comment by EliseAndresen** [comment]
![Screenshot_20221012-150330_Chrome](https://user-images.githubusercontent.com/112557835/195359441-d40b3a5f-9199-4a8e-8964-a101dd9beb52.jpg)

Title with long words overflow on mobile view in articles.

**Comment by EliseAndresen** [comment]
![Screenshot_20221012-150353_Chrome](https://user-images.githubusercontent.com/112557835/195361759-6f2f8316-7efe-4471-bba0-a013530e5705.jpg)

Bullet points within bullet points is a bit crammed on mobile. Could we adjust it so that there is no indentation on the first instance and the text in the second bullet point has a bit more space?

**Comment by EliseAndresen** [comment]
![Screenshot_20221012-151232_Chrome](https://user-images.githubusercontent.com/112557835/195364339-2b7b0b0f-5469-414f-ad18-207c9f3d4e4d.jpg)

Min side -> donasjoner
Something renders wrong here. Happens when you enter the overview page of donations on small/mobile screen and you have no donations yet

**Comment by EliseAndresen** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/112557835/195366055-0ef37bed-8a25-4c76-9100-dcd22541eaca.png">

Personvernerklæring title is too wide.

**Comment by EliseAndresen** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/112557835/195366447-9cf911c4-7f81-414c-b6e0-a6971d4957df.png">

Text and separator line on personverns page have too much padding/margin on the right.

**Comment by EliseAndresen** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/112557835/195366754-8953b24d-af85-4d26-9ff0-6596a4583642.png">

Impact widget buttons are too close together on mobile.

**Comment by EliseAndresen** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/112557835/195367133-723b3a84-2892-46b0-a481-7d0effb92e31.png">

Donation widget on mobile has very small buttons in the bottom.

**Comment by EliseAndresen** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/112557835/195368699-f25a1907-dde1-4b1d-a926-805f83e58a6c.png">

Maks effekt title is very small and disappears somewhat on all screen sizes.
